name: scheduled build & push of latest version

on:
  schedule:
    - cron: '0 3 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    name: build and publish Docker image
    steps:
      - name: checkout code to list tags
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: set latest tag var
        id: latestTag
        run: echo ::set-output name=tag::$(git tag -l 'v*' --sort=taggerdate | tail -n 1 | cut -d 'v' -f 2)
      - name: checkout latest tag
        uses: actions/checkout@v2
        with:
            ref: v${{ steps.latestTag.outputs.tag }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          tags: |
            delker/traefik-forward-auth-modopenidc:latest
            delker/traefik-forward-auth-modopenidc:${{ steps.currentTag.outputs.tag }}
          push: true
